package org.zhku.HanxiMall.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class Dealer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer.id
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer.dealer_name
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    private String dealerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer.dealer_password
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    private String dealerPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer.level_name
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    private String levelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer.level
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer.phone
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer.father_id
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    private String fatherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer.regist_time
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    private Date registTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer.grant_code
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    private String grantCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer.address
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer.sex
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer.money
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    private BigDecimal money;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer.id
     *
     * @return the value of dealer.id
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer.id
     *
     * @param id the value for dealer.id
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer.dealer_name
     *
     * @return the value of dealer.dealer_name
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public String getDealerName() {
        return dealerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer.dealer_name
     *
     * @param dealerName the value for dealer.dealer_name
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public void setDealerName(String dealerName) {
        this.dealerName = dealerName == null ? null : dealerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer.dealer_password
     *
     * @return the value of dealer.dealer_password
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public String getDealerPassword() {
        return dealerPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer.dealer_password
     *
     * @param dealerPassword the value for dealer.dealer_password
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public void setDealerPassword(String dealerPassword) {
        this.dealerPassword = dealerPassword == null ? null : dealerPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer.level_name
     *
     * @return the value of dealer.level_name
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public String getLevelName() {
        return levelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer.level_name
     *
     * @param levelName the value for dealer.level_name
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public void setLevelName(String levelName) {
        this.levelName = levelName == null ? null : levelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer.level
     *
     * @return the value of dealer.level
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer.level
     *
     * @param level the value for dealer.level
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer.phone
     *
     * @return the value of dealer.phone
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer.phone
     *
     * @param phone the value for dealer.phone
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer.father_id
     *
     * @return the value of dealer.father_id
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public String getFatherId() {
        return fatherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer.father_id
     *
     * @param fatherId the value for dealer.father_id
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public void setFatherId(String fatherId) {
        this.fatherId = fatherId == null ? null : fatherId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer.regist_time
     *
     * @return the value of dealer.regist_time
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public Date getRegistTime() {
        return registTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer.regist_time
     *
     * @param registTime the value for dealer.regist_time
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public void setRegistTime(Date registTime) {
        this.registTime = registTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer.grant_code
     *
     * @return the value of dealer.grant_code
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public String getGrantCode() {
        return grantCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer.grant_code
     *
     * @param grantCode the value for dealer.grant_code
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public void setGrantCode(String grantCode) {
        this.grantCode = grantCode == null ? null : grantCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer.address
     *
     * @return the value of dealer.address
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer.address
     *
     * @param address the value for dealer.address
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer.sex
     *
     * @return the value of dealer.sex
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer.sex
     *
     * @param sex the value for dealer.sex
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer.money
     *
     * @return the value of dealer.money
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer.money
     *
     * @param money the value for dealer.money
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }
}