package org.zhku.HanxiMall.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class Dealer_stock {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer_stock.id
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer_stock.price
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer_stock.count
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer_stock.create_time
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer_stock.update_time
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer_stock.dealer_id
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    private Integer dealerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer_stock.product_id
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    private Integer productId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer_stock.id
     *
     * @return the value of dealer_stock.id
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer_stock.id
     *
     * @param id the value for dealer_stock.id
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer_stock.price
     *
     * @return the value of dealer_stock.price
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer_stock.price
     *
     * @param price the value for dealer_stock.price
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer_stock.count
     *
     * @return the value of dealer_stock.count
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer_stock.count
     *
     * @param count the value for dealer_stock.count
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer_stock.create_time
     *
     * @return the value of dealer_stock.create_time
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer_stock.create_time
     *
     * @param createTime the value for dealer_stock.create_time
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer_stock.update_time
     *
     * @return the value of dealer_stock.update_time
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer_stock.update_time
     *
     * @param updateTime the value for dealer_stock.update_time
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer_stock.dealer_id
     *
     * @return the value of dealer_stock.dealer_id
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public Integer getDealerId() {
        return dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer_stock.dealer_id
     *
     * @param dealerId the value for dealer_stock.dealer_id
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public void setDealerId(Integer dealerId) {
        this.dealerId = dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer_stock.product_id
     *
     * @return the value of dealer_stock.product_id
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer_stock.product_id
     *
     * @param productId the value for dealer_stock.product_id
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
}