package org.zhku.HanxiMall.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class Orders {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.id
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.create_time
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.complete_time
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    private Date completeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.address
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.count
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.remarks
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.price
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.state
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.send_dealer_id
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    private Integer sendDealerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.product_id
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.get_dealer_id
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    private String getDealerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.create_time
     *
     * @return the value of orders.create_time
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.create_time
     *
     * @param createTime the value for orders.create_time
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.complete_time
     *
     * @return the value of orders.complete_time
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public Date getCompleteTime() {
        return completeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.complete_time
     *
     * @param completeTime the value for orders.complete_time
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public void setCompleteTime(Date completeTime) {
        this.completeTime = completeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.address
     *
     * @return the value of orders.address
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.address
     *
     * @param address the value for orders.address
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.count
     *
     * @return the value of orders.count
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.count
     *
     * @param count the value for orders.count
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.remarks
     *
     * @return the value of orders.remarks
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.remarks
     *
     * @param remarks the value for orders.remarks
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.price
     *
     * @return the value of orders.price
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.price
     *
     * @param price the value for orders.price
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.state
     *
     * @return the value of orders.state
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.state
     *
     * @param state the value for orders.state
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.send_dealer_id
     *
     * @return the value of orders.send_dealer_id
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public Integer getSendDealerId() {
        return sendDealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.send_dealer_id
     *
     * @param sendDealerId the value for orders.send_dealer_id
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public void setSendDealerId(Integer sendDealerId) {
        this.sendDealerId = sendDealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.product_id
     *
     * @return the value of orders.product_id
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.product_id
     *
     * @param productId the value for orders.product_id
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.get_dealer_id
     *
     * @return the value of orders.get_dealer_id
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public String getGetDealerId() {
        return getDealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.get_dealer_id
     *
     * @param getDealerId the value for orders.get_dealer_id
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    public void setGetDealerId(String getDealerId) {
        this.getDealerId = getDealerId == null ? null : getDealerId.trim();
    }
}