package org.zhku.HanxiMall.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.zhku.HanxiMall.pojo.Dealer;
import org.zhku.HanxiMall.pojo.DealerExample;

public interface DealerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealer
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    long countByExample(DealerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealer
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    int deleteByExample(DealerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealer
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealer
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    int insert(Dealer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealer
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    int insertSelective(Dealer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealer
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    List<Dealer> selectByExample(DealerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealer
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    Dealer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealer
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    int updateByExampleSelective(@Param("record") Dealer record, @Param("example") DealerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealer
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    int updateByExample(@Param("record") Dealer record, @Param("example") DealerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealer
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    int updateByPrimaryKeySelective(Dealer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealer
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    int updateByPrimaryKey(Dealer record);
}