package org.zhku.HanxiMall.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.zhku.HanxiMall.pojo.Dealer_stock;
import org.zhku.HanxiMall.pojo.Dealer_stockExample;

public interface Dealer_stockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealer_stock
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    long countByExample(Dealer_stockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealer_stock
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    int deleteByExample(Dealer_stockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealer_stock
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealer_stock
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    int insert(Dealer_stock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealer_stock
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    int insertSelective(Dealer_stock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealer_stock
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    List<Dealer_stock> selectByExample(Dealer_stockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealer_stock
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    Dealer_stock selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealer_stock
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    int updateByExampleSelective(@Param("record") Dealer_stock record, @Param("example") Dealer_stockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealer_stock
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    int updateByExample(@Param("record") Dealer_stock record, @Param("example") Dealer_stockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealer_stock
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    int updateByPrimaryKeySelective(Dealer_stock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealer_stock
     *
     * @mbg.generated Mon Aug 03 11:07:32 CST 2020
     */
    int updateByPrimaryKey(Dealer_stock record);
}